### PR TITLE
Allow user to decide the HTTP user agent

### PR DESCRIPTION
**Pull request by mikkoi**
Use HTTP::AnyUA to allow the package to decide which HTTP user agent
he wants to use, e.g. LWP::UserAgent, HTTP::Tiny, Furl.

Backwards compatible: if no user agent is given, then use Furl like before.
Furl is made a recommended dependency, not required anymore.

Attn. All tests which use mocking fail now because Furl is no longer
used normally, i.e. there is no "use Furl;". The "use Furl" now happens
within an eval because if user specifies another agent, then Furl 
does not need to be installed at all.

Signed-off-by: Mikko Johannes Koivunalho <mikko.koivunalho@iki.fi>

### CODE REVIEW

**Comment by mihyaeru21** [comment]
> Attn. All tests which use mocking fail now because Furl is no longer
> used normally, i.e. there is no "use Furl;". The "use Furl" now happens
> within an eval because if user specifies another agent, then Furl
> does not need to be installed at all.

I'll think about it on next weekend :ok_hand: Maybe, I'll use something like mock object for `ua` to solve it.

Please rebase from master branch. Then all tests are run through CI. I fixed CI config on #40 .

**Comment by mihyaeru21** [comment]
@mikkoi 
I fixed tests in https://github.com/mikkoi/p5-WebService-Slack-WebApi/pull/1 👍  How about this?

**Comment by mikkoi** [comment]
Great. Thank you. All tests pass.

Test coverage dropped slightly.
https://coveralls.io/builds/35473661/source?filename=lib/WebService/Slack/WebApi/Client.pm
But nothing that matters.

**Review by mihyaeru21 — APPROVED** [review]
👍

**Pull request merged**
